### ISSUE TITLE
set_collection_interval does not exist

### ISSUE THREAD

**Issue by akuzminsky** [greenlion/ps_history#2]
```
mysql> CALL ps_history.set_collection_interval(60);
ERROR 1305 (42000): PROCEDURE ps_history.set_collection_interval does not exist
```

**Comment by akuzminsky** [comment]
Correct name is `ps_history.set_collect_interval()`

**Comment by greenlion** [comment]
Hi,

You can submit a patch, or I can get it corrected later this week.  Thanks
for trying it out!

--Justin

**Comment by greenlion** [comment]
There is now get_collection_interval which just calls get_collect_interval for consistency.
