### ISSUE TITLE
Collection interval deviates from configuration value

### ISSUE THREAD

**Issue by akuzminsky** [greenlion/ps_history#3]
I was running ps_history with default 30 seconds collection interval. The actual interval is higher though:

```
mysql> select distinct ts from users order by ts;
...
| 2016-02-10 19:22:20.13353 |
| 2016-02-10 19:22:58.21372 |
| 2016-02-10 19:23:37.22560 |
| 2016-02-10 19:24:16.23163 |
+---------------------------+
973 rows in set (0.01 sec)
```

As you can see it's approximately 40 seconds. The skew happens because it takes about 10 seconds to take a copy of PS state. Maybe it makes sense to move this piece:

```
        DELETE FROM ps_history.psh_last_refresh;
        INSERT INTO ps_history.psh_last_refresh VALUES (now());
```

to the top of `ps_history.collect()`.

**Comment by greenlion** [comment]
Good idea.

**Comment by greenlion** [comment]
I have to spin up a new VM, but i'll get to the bugs you reported shortly.
